services:
  php:
    build:
      context: ./docker
      target: php-dev
      args:
        XDEBUG_ENABLED: ${XDEBUG_ENABLED-false}
    depends_on:
      - db
    volumes:
      - ./:${CODE_MOUNT_PATH}:delegated
    environment:
      - PHP_IDE_CONFIG
      - XDEBUG_CONFIG
      - DB_HOST=db
      - DB_NAME
      - DB_USER
      - DB_PASSWORD

  nginx:
    build:
      context: ./docker
      target: nginx-dev
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./:${CODE_MOUNT_PATH}:delegated

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env

  redis:
    image: redis:latest
    volumes:
      - redis:/data

volumes:
  db:
  redis: